language: generic

go:
  - 1.12.x

env:
  - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest

stages:
  - build
  - deploy

services:
  - docker

jobs:
  include:
    - stage: build
      os: linux
      arch: amd64
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
      on:
        tags: false
    - stage: build
      os: linux
      arch: ppc64le
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
    - stage: deploy
      os: linux
      arch: amd64
      dist: bionic
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
        - . ./ci/release.sh
      before_deploy:
        - . ./ci/release.sh
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ci/release/*
      file_glob: true
      on:
        tags: true
        repo: CameronMcwilliam/stacks
        branch: multiArch
