language: generic

go:
  - 1.12.x

env:
  - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest

stages:
  - build
  - deploy

services:
  - docker

before_deploy:
  - . ./ci/release.sh

jobs:
  include:
    - stage: build
      os: linux
      arch: ppc64le
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
    - stage: deploy
      env:
        - DOCKER_EXPERIMENTAL_CLI=enabled
      os: linux
      arch: amd64
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ci/release/*
      file_glob: true
      on:
        tags: true
        repo: CameronMcWilliam/stacks
        branch: multiArch
