language: generic

go:
  - 1.12.x

stages:
  - build
  - deploy

services:
  - docker

jobs:
  include:
    - stage: build
      env:
        - TRAVIS_STAGE=build
        - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest
      os: linux
      arch: amd64
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
    - stage: build
      env:
        - TRAVIS_STAGE=build
        - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest
      os: linux
      arch: ppc64le
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script: 
        - . ./ci/build.sh
    - stage: deploy
      env:
        - TRAVIS_STAGE=deploy
        - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest
      if: tag IS present
      os: linux
      arch: amd64
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script:
        - . ./ci/build.sh
        - pwd
        - ls -la ./ci/
        - . ./ci/release.sh
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ci/release/*
      file_glob: true
      on:
        condition: "$PRIMARY_ARCH = true"
        tags: true
        repo: CameronMcwilliam/stacks
        branch: multiArch
    - stage: deploy
      env:
        - TRAVIS_STAGE=deploy
        - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest
      if: tag IS present
      os: linux
      arch: ppc64le
      dist: bionic
      install: . ./ci/git_setup.sh
      before_script: ./ci/download_cli.sh
      script:
        - . ./ci/build.sh
        - . $script_dir/release.sh
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ci/release/*
      file_glob: true
      on:
        condition: "$PRIMARY_ARCH = true"
        tags: true
        repo: CameronMcwilliam/stacks
        branch: multiArch