language: generic

go:
  - 1.12.x

env:
  - APPSODY_CONTROLLER_IMAGE=cameronmcwilliam/init-controller:latest

stages:
  - build
  - deploy

services:
  - docker

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/git_setup.sh
  - . ./ci/download_ci.sh
  - . ./ci/build.sh
  - . ./ci/push.sh
  - . ./ci/release.sh


jobs:
  include:
    - stage: build
      os: linux
      arch: amd64
      dist: bionic
      script: 
        - . ./ci/git_setup.sh
        - . ./ci/download_ci.sh
        - . ./ci/build.sh
        - . ./ci/push.sh
      on:
        tags: false
    - stage: build
      os: linux
      arch: ppc64le
      dist: bionic
      script: 
        - . ./ci/git_setup.sh
        - . ./ci/download_ci.sh
        - . ./ci/build.sh
        - . ./ci/push.sh
    - stage: deploy
      env:
        - DOCKER_EXPERIMENTAL_CLI=enabled
      os: linux
      arch: amd64
      dist: bionic
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ci/release/*
      file_glob: true
      on:
        tags: true
        repo: CameronMcWilliam/stacks
        branch: master